# Introduction {#intro}
Anthropogenic activity in the last few decades will continue to influence the interations within and among ecological systems worldwide. The complexity and drivers of changes in coupled human-natural systems is consequently altered, further limiting our ability to detect and predict change and impacts of change [@liu_complexity_2007; @scheffer_critical_2009]. Early warning systems are developed to detect,  and in some cases predict, abrupt changes in disparate systems [e.g. cyber security @kaufmann2015structural; banking and stock markets @davis_comparing_2008]. The need to develop and improve early warning systems for natural and coupled human-natural systems is exacerbated by the consequences of climate change and globalization, especially when the human-related stakes are high. The ecological literature is inundated with quantitative methods and models with the promise of predicting abrupt change in high-dimensional ecological systems in time for intervention. The paucity of application of many of these methods by practitioners and decision makers suggests much work is to be done in advancing both our understanding of abrupt ecological change and of the methods used for detecting it. 

Forecasting undesirable change is, arguably, the holy grail of ecology. Paired with an understanding of system interactions, a forecast is ideal if it provides reliable forecasts with sufficient time to prevent or mitigate unwanted systemic change. Early warning systems (or early warning signals, or early warning indicators) have been developed and tested for some ecological systems data, but have been mostly applied to marine fishies time series and nutrient loadings in shallow lakes. Despite the numerous quantitative methods [see Chapter \@ref(rdmReview)] proposed as early warning systems for ecological data, many are currently of limited practical utility. This paradox may be a consequence of existing  early warning systems  having one or more of the following characteristics:

  1. Not generalizable across systems or system types (especially when it requires a model or a determinsitic function to describe the system) 
  1. Requires a large number of observations
  1. Difficult to implement
  1. Difficult or to interpret 
  1. Requires an understanding of the drivers of change
  1. Performs poorly under uncertainty and in presence of noise
  1. Gives no uncertaintiy around estimates (tying into interpretation issues)
  <!-- 1. Cannot handle noisy data -->
  1. Ignores or does not sufficiently account for observation error
  1. Currently no baseline with which to compare results
  1. Currently no application/testing on empirical systems data
  1. Systems are subjectively bounded (i.e., components are chosen)
  1. Being overshadowed by semantics
  1. Are based on before-and-after information
  1. Cannot link the shift to potential drivers (i.e. the method reduces the dimensionality such that it is unitless and/or loses all relevant information)
  1. Cannot handle irregular sampling 
  1. Cannot handle non-smooth or non-linear data

Research focusing on the above areas as they relate to regime detection measures will can only advance and improve of these early warning systems, further shedding light on the potential of these methods for application to place-based  observations.

## Dissertation aims
The overarching aim of this dissertation is to contribute to our understanding of the utility and limitations of early warning systems for ecological regime detection, which I will refer to as 'regime detection measures'. Regime detection measures exist for handling both univariable and multi-variable data, however, it is the latter of these methods within which this dissertation focuses. Although the univariate regime detection measures are currently more widely applied and conceptually tractable than many multivariate regime detection measures, the utility of the univariable measures may be limited when change(s) in the system dynamics manifest in entire community dynamics, rather than in select indicator species, for example. Multivariable regime detection measures may also be more advantageous than analysing individual variables when the drivers of the observed systemic change are unknown. Further, ecological systems are noisy, and ecological systems data are messy --- conditions difficult to handle using univariable regime detection measures.



## Dissertation structure
### Chapter highlights and chronology
This dissertation comprises a glossary (section \@ref(definitions)), eight distinct Chapters (Chapters \@ref(intro)-\@ref(conclusions)), and compendium of open-source statistical software authored during the production of this dissertation in the form of two appendices (Appendices \@ref(regimeDetectionMeasures)- \@ref(bbsRDM)). Finally, the dissertation is synthesized in Chapter \@ref(conclusions). 

**Section\@ref(definitions)**. The terminology associated with this line of research is highly variable both within and outside the field of ecology. For example, although many core concepts informing ecological regime shift theory stem from dynamical systems theory, the terminologies do not align [@andersen_ecological_2009; @hastings2010regime]. Therefore to ensure clarity of discussion throughout this work, I provide a glossary of phrases and concepts related to this dissertation in a front-matter glossary (section \@ref(definitions)). 

**Chapter  \@ref(rdmReview)**. There exists a staggering number of quantitative methods for identifying abrupt changes and regime shifts in ecological systems data. Despite the high number of methods proposed in the literature, few have been scrutinized against empirical data, and even fewer applied to multiple types of systems (e.g., terrestrial mammals vs. marine fisheries). Although numerous reviews of these methods are published, few are comprehensive in their presentation of the proposed methods and metrics. In this Chapter \@ref(rdmReview) I conducted a formal literature review  to both present a comprehensive source for identifying regime detection methods. 

**Chapter \@ref(fiGuide)**. Fisher Information is proposed as method for identifying regime shifts in multivariable ecological time series and spatially-explicit data and has been applied to a variety of systems across at least 20 publications. Two forms of this measure exist, one of which (the 'derivaitves-based' method) requires fewer steps and *a priori* defined parameters to calculate than the other (the 'binning method'). Chapter \@ref(fiGuide) contributes to the  understanding of the 'derivatives-based' Fisher Information as a regime detection measure in two ways. First, I present a step-by-step overview of both the logistics and concepts required for calculating this measure. Next, I suggest that the current calcualtion of Fisher Information can be split into two distinct parts: a dimensionality reduction and the actual calculation of the Fisher Information. This results of this study has implications for how the method can be used in the future, and whether it will suffice as an indicator of abrupt change under certain conditions.

**Chapter \@ref(fisherSpatial)**. The Fisher Information method has been applied both temporal [@cabezas_san_2010] and spatial empirical data [@eason2019information;@sundstrom2017detecting]. To demonstrate the utility of Fisher Information in identifying abrupt change in ecological communities at large spatial scales, I present an application of Fisher Information to spatially-explicit avian community data in North America.


**Chapter \@ref(velocity)**. Building off of the method described in Chapter \@ref(fiGuide) I suggest a method which I refer to as 'velocity' method for identifying ecological regime shifts. Previous use of the velocity metric has been embedded within larger calculations of Fisher Information, specifically in the 'derivatives-based' method (see Chapter \@ref(fiGuide)). The velocity method is an overlooked, simple calculation that may be useful in identifying abrupt changes in high dimensional temporal or spatial series. Here, I thoroughly describe the calculations behind the velocity metric, and demonstrate its utility through application to both simulated and empirical systems data. 

**Chapter \@ref(resampling)**. Of the numerous regime detection measures published (see Chapter \@ref(rdmReview)), few have been applied to empirical multivariate ecological data, and even fewer scrutinized as indicators of abrupt  change. In this Chapter I compare the ability of select regime detection measures to identify published abrupt changes in a paleodiatom community. Further, I examine the results of these measures under various conditions of data quality and quantity (e.g., missing species, infrequent sampling) using resampling methods. This Chapter also provides a critical starting point for determining the utility of the velocity method (proposed in Chapter \@ref(velocity)) versus other techniques. 

**Chapter \@ref(discontinuity)**. This chapter presents an application of body mass discontinuity analysis to avian community time series before and after a landscape-scale regime shift [@roberts2019shifting]. In this chapter, I test the hypothesis that declining and other species sensitive to grassland habitat loss and degradation operate the edges of body mass aggregations. Although I find evidnece suggesting declining and sensitive (grassland obligate) species operate near the edges of body mass disributions as opposed to other species, I was unable to identfiy clear patterns in the avian community body mass distributions using a before-and-after design with respect to the proposed spatial regme [@roberts2019shifting]. Appendix \@ref(discontinuity) contains an annotated version of the code for the functions used to identify discontinuities in avian body mass distributions [originally published in @barichievy2018method]. 

### Software Appendices 
Appendices \@ref(regimeDetectionMeasures) and \@ref(bbsRDM) contain manuals for two, self-authored softwares used througout this dissertation. They are available for download at www.github.com/trashbirdecology.  

#### R package: `regimeDetectionMeaures` 
Appendix \@ref(regimeDetectionMeasures) contains code for calculating a suite of regime detection measures, including the traditional early-warning indicators, Fisher Information, and the velocity metric. 

#### R package: `bbsRDM`
Appendix \@ref(bbsRDM) contains functions for conducting spatial and temporal anlaysis of the regime detection measures contained in package `regimeDetectionMeasures` (Appendix \@ref(regimeDetectionMeasures)), and is closely aligned with the analyses in Chapters \@ref(fisherSpatial) and \@ref(resampling). Further, this package provides a wrapper for downloading and munging data from the U.S. Geological Survey's Breeding Bird Survey, munging said data, and creating spatial sampling grids across North America. Minor additional functionality includes an option to download and identify U.S. military bases across the globe. 

