# Quantitative indicators of abrupt ecological change {#indicators-chapter}   

<!-- I might include this section as the introduction to multiple chapters, but for now I will just write it as a separate, brief section. -->





[@chuang_enhancing_2018 complexity]

ewsystems are reduced when the uncertainties are high -- 

. The ability When the stakes associated with some systems are high, the ability to  is desirable. 

s, e.g. agricultural systems and extreme weather events, are high--human lives

understThe stakes in some systems is high, especially when the system is nearing or has surpassed a state from which it is difficult to recover ( __tipping point__). Systems with tipping points exist in social, economic, and ecological systems worldwide and operate at multiple scales. __Early warning systems__, or indicators that a system is nearing a supposed tipping point, are prevalent in many fields 



Climate change and globalization has been blamed triggering undesirable changes in agricultural systems and natural resource supplies (fish ref; ag ref), influenced the frequency and intensity of extreme weather events (ref), and [@dakos_slowing_2008]
banking crisis [@davis_comparing_2008]

Early warning systems are well-developed for systems explained by a single variable or when drivers of the shift are suspected. For example, 

This is especially so for fisheries 

[@gramlich_early_2010] - review of banking early warning systems


Detection and prediction of undesirable changes is the focus of many systems (e.g., network security, economies and currencies, ) 
Early-warnings of changes in systems is prevalent 
__Regime shifts__ are defined as changes in either the structure  or underlying functioning of a system.

Identifying historic ecolgoical regime changes has been achieved using post-hoc analyitcal approaches, and many have been tested and verified in multiple systems. Methods for reliably forecasting and predicting these changes are less common. Although numerous quantitative methods exist for detecting ecological regime shifts, new methods are proposed for achieving this aim ata  XXX rate (*insert figure of number of papers per year with new methods*). These methods have proven useful in detecting shifts in atmospheric and fisheries catch data, and in systems that are well-described by a few state variables, or can be modelled reliably with matheamtical equations. Because ecological comunities are more complex than, say, a simple Lotka-Volterra predator prey system, the set of reliable regime shift detection methods narrows. 

Ecological and social-ecolgical systems havemany unpredictable and variably interacting components. Systems analyses, including Dynamic Bayesian Networks, network models, and food webs are designed to handle these complexities, yet obtaining enough information to feed these models seems less feasible in ecosystem research and management. A survey of the methods available for detecting ecological regime shifts in high dimensional data is timely. Recent reviews of regime shift indicators (Andersen et al, the others) are outdated, are not comprehensive (include only a subset of the available RSDMs), and do not provide recommendations for which events, systems, or data characterstics are appropriate for these methods. 

Some RSDMs are proposed for and are subsequently applied to data having specific characteristics, while others are proposed to be useful in multiple systems and on data of varying characterstics (e.g., Karunithi et al; Mayer 2007; Eason). This review provides a summary of the available methods and evaluates the appropriateness of these methods to data of varying character, quality, and quantity.

This paper aims to identify, describe, and critique quantitative RSDMs that have been used or proposed to detect regime shifts in ecological data. We discuss the relevant characteristics of the data/information that are required for each method, and how these characterstics may help or hinder the ecologists' interpretation of the analytical results. We pay special attention to the RSDMs that are most appropriate for  analysis of high dimensional and noisy ecological data. 


## Methods

### Identifying papers/RSDMs in the literature
1. We conducted a systematic review using the software Publish or Perish to identify unique statistical and numerical methods that have been used to identify ecological regime shifts. We used the following databases to identify scholarly works that introduce and/or explain methods for identfying regime shifts:  
    i. __Database searches*  
          a. Boolean (+ = asterisk in the database search)  
                i. WOS:   
                ii. SCOPUS:  ( TITLE-ABS-KEY ( ( approach  OR  analysis  OR  metric  OR  method^ )  AND  ( detect^  OR  predict^ ) )  AND  TITLE-ABS-KEY ( {regime shift}  OR  {regime change}  OR  {abrupt change} ) ) __1,473__ (where ^== __ in Scopus) 
    ii. __Opportunistic papers__  
          a. We used expert opinion (authors JLB, etc.) to identify any missing RSDMs that were not detected in our formal database searches. (i am making this next part up--need to double check once i have results)-->These papers are are typically found in the grey literature, or are published in journals not obvious to the general ecologist (e.g., name an obscure journal here).  
          b. Justification for our database searches containing some of these methods which are known/obvious to the author(s).  

2. Procedures for filtering the papers.     
    i. We removed duplicate titles (from the merging of Scopus and WOS), which resulted in _______ unique scholarly works.    
    i. We read the abstracts of each paper to determine the following:    
          a. Was this a new method being proposed or used? (if yes, proceed to ii.))    
          b. Was this just a case study or another application of a previously published method? (if yes, note the method(s) used and identify original method(s) source)      
          c. If this paper was an application of a method, we noted the method, and identified the orignal source for the method (if possible)  
    ii. Identify characteristics of the method  
        c. It is model-based?  
        a. Does it require a mathematical model?
        b. Does it require *a priori* knowledge of the regime shift
        d. Does it forecast or provide predicitons?
        e. Assumptions required (e.g., discontinuity, step functions, normality of response vars)
    iii. Identify requirements for the data input
        a. Require equal spacing b/w observations?
        b. Minimum # data points required to use?
        c. Minimum # of state variables required?
    iv. Identify the characteristics of the data USED to demonstrate the method
        a. Spatial resolution and extent
        b. Temporal resolution and extent
        c. Number of state variables 
        d. System type 
          i. Whole-system vs. selected variables?
          ii. Experimental system or observational/passive
3. Note the number of times the paper has been cited
  

## Results

We identified _______ number of quantiattive anlaytical approaches to identifying regime shifts and abrupt changes in data. 

### Potential figures

1. X = year Y = number of publications for *new* RSDMs in the ecol/env literature
1. X = year Y = # pubs for new RSDM appropriate for multidimensional systems


### Potential tables

<!-- \newpage -->
<!-- \blandscape -->
<!-- ```{r  echo=FALSE, message=FALSE, warnings=FALSE, label = "characteristicsResults"} -->
<!-- colNames <- t(c('Authors', "Year of Publication", "Dimensionality of data", "Longitudinality of data", "Method applied")) -->

<!-- knitr::kable( -->
<!--   colNames, longtable = TRUE, booktabs = TRUE, -->
<!--   caption = 'Data structure and analytical procedures characteristics fo the selected studies.' -->
<!-- ) -->

<!-- ``` -->
<!-- \elandscape -->

## Discussion 

1. Major findings of the review. 
1. What major assumptions are we currently making about the data and the system that we need to know more about moving forward? i.e., where are the gaps in knowledge?
1. How has or how can we take advantage of unstructured or semi-structured data to ID regime shifts?
1. How can or should we adapt our monitoring schemes to better suit these (or at least the seemingly helpful) analyses?
1. What about identifying the drivers behind the shifts? 
1. Which methods posit they can identify the, or potential, drivers of the state changes? Which have shown it?

Potential text: 
1. Climate change is expected to induce an increase in both the intensity and frequency of rapid ecological change or disturbance, impacting social systems, potentially to the detriment of human communities most vulnerable. Identifying and forecasting these changes is critical for community and ecological planning, management, and disaster mitigation. 

1. Because ecological and social systems are tightly coupled, we have used indicators in the environment and in wildlife communities to identify change and potential changes that may impact our social communities. 

1. Many regime shift analytical papers suggest that, using multiple quantitative methods to provide for evidence for a regiem shift in a specific data set is necessary or is acceptable. Although this proposition is valid, comparing results within a single system using multiple methods has often yielded varying results. Managing systems using quantitative methods that yield different results may yield improper management techniques and objectives. 

