# Data Quality Impacts on Regime Detection Measures  {#resampling}
**SEE IIASA REPORT** (.doc)
```{r cache = TRUE, echo=FALSE, warning=FALSE, eval=TRUE, message=FALSE, results="hide"}
# Chunk defaults
# require(knitr)
knitr::opts_chunk$set(cache = TRUE, cache.path = "_cache/", message = FALSE, warning=FALSE, eval=TRUE, echo=FALSE, error=FALSE, fig.align='center', out.width = "85%")
```
## Introduction 
Ecological systems have many unpredictable and variably interacting components (Jørgensen et al. 2011). Methods for analyzing these complex systems, e.g. Dynamic Bayesian Networks, network models, and food webs are designed to handle these complexities, yet require data- and knowledge-intensive models. Although ecological data collection and data management techniques are improving (La Sorte et al. 2018), the aforementioned approaches to modeling and understanding complex system are often infeasible in ecosystem research and management (Clements et al. 2015). 

A growing concern with anthropogenic impacts on the environment has increased the demand for mathematical and statistical techniques that capture these dynamics. These often undesirable changes in the structure or functioning of ecological systems are often referred to as “regime shifts”, “regime changes”, “state change”, “abrupt change”, etc. (Andersen et al. 2009) . A yet-unattained goal of ecological research and management is to reach a point where these methods can predict impending regime shifts in real-time and with high confidence. Ideally, ecological regime shift detection methods (hereafter, RDMs) would require little knowledge of the intrinsic drivers of the system, and the users of the method would not be required to know if and where a regime shift occurred in the data. 

Despite the suite of RDMs in the environmental and ecological research literatures, they are not used in ecological management. We can describe the current state of RDMs as being either system–specific (i.e., the method is not widely applicable or generalizable across systems) or not. Methods of the latter type are convenient in that they can be applied across various system and data types, but the results of these analyses require some degree of subjective interpretation (Clements and Ozgul 2018; c.f. Batt et al. 2013). Efforts to develop and/or improve RDMs that can handle these biases will aid the advance of RDMs research and application. 

Current efforts to improve RDMs may be stunted by the lack of application beyond simple and/or theoretical (toy) systems data. Like most statistical and mathematical approaches, the evolution of many RDMs begins with application to theoretical data, followed by application to empirical data. Current applications of RDMs to empirical, ecological data are largely limited to data describing populations (e.g., Anderson and Piatt 1999, Alheit et al. 2005, deYoung et al. 2008), climatic, marine (e.g., Lipizer et al. n.d., Nicholls 2011),  and Paleolithic regime shifts (Spanbauer et al. 2014, Yang et al. 2017, Kong et al. 2017),  with few applications terrestrial data (c.f. Bahlai et al. 2015, Sundstrom et al. 2017). Although testing the performance and inference boundaries of theoretical and simple systems is important, they are of little use to ecosystem managers if they are not proven to be easily and reliably applicable to their system. Additionally, RDMs should be capable of handling diverse and often noisy field data.  

Ecological systems data is not only expensive and is difficult to capture, but is also notoriously imperfect—that is, process and observation error are common in these data. The resulting variability in data quality and quantity limits the numerical tools available for detecting ecological regime shifts (Thrush et al. 2009). Some methods, new and old, are proposed in the literature as RDMs which are capable of handling data limitation and quality issues inherent in ecological data and require few subjective decisions for choosing state variables and interpreting results. For example, variable reduction techniques, e.g. principal components analysis (Rodionov 2005, Andersen et al. 2009, Reid et al. 2016) and clustering algorithms (Weijerman et al. 2005, Weissmann and Shnerb 2016), an index of variance (Brock and Carpenter 2006) and Fisher Information (Cabezas and Fath 2002, Fath and Cabezas 2004, Karunanithi et al. 2008) were introduced as methods which collapse the system into a single indicator of ecological regime shifts. 

The transferability of RDMs to practitioners can only be facilitated by identifying intuitive metrics and testing the capacity of RDMs to handle high dimensional, empirical data. Here, we present a method for tracking the trajectory of an n-dimensional system using a single metric and its derivative. Here, I describe provide a description of this metric and apply it to empirical systems data. I then compare the results of this new metric to two other multivariate, model-free metrics: the Variance Index [@brock_carpenter_2005] and Fisher Information [@cabezas__2002; \@ref(fiGuide)]. Finally, we explore how decisions made during the data collection and data analysis phases impact these metrics.

## Methods
### Study system and data  
I jackknifed paleodiatom time series from a freshwater system in North America which exhibited a rapid shift in community dynamics. These data were collected using a sediment coring method [see @spanbauer_detecting_2014]. Community profiles at various depths within sediment cores are analyzed to obtain relative abundances. Relative abundances at various depths within the sediment core are then related to time (years before present) using carbon dating techniques. These data can be obtained from the publisher’s website. 

### Regime detection measures

I use multiple methods for identifying regime shifts. 


#### Variance index  

#### Fisher Information  

#### System velocity, $v$
In Chapter \@ref(velocity), I describe a 'new' method, __system velocity__, $v$, as a potential dimension reduction and regime  detection method. Although this is the first instance of this calculation to, alone, be suggested as a regime detection metric, it has been used as part of a larger series of calculations of the Fisher Information metric. First introduced in by @fath_regime_2003 as one of multiple steps in calculating their variant of Fisher Information, system velocoty represents the cumulative sum of the squared change in all state variables over a period of time. Steps for calculating this metric are described in great detail in Chapters \@ref(fiGuide) and \@ref(velocity). 



## Results
SEE IIASA REPORT

## Discussion 

## Ackowledgements
This study was conceptualized at the International Institute for Applied Systems Analysis (IIASA) as part of the Young Scholars Summer Program in 2018. I thank my IIASA program supervisors, Drs. Brian Fath and Elena Rovenskaya, for advisement during this period and for comments on an earlier version of this chapter.