# Discontinuity chapter under construction {#discontinuity}

## Introduction
Body size influences the frequency and intensity of inter- and intraspecific competition for resources, territory, and mates, thereby dictating the spatial and temporal scales at which a species of a distinct body size operates [@peters1983effect;@silva1995allometric; @allen2006patterns]. The scaling structure of terrestrial communities are have been found to have 'lumpy' distributions --- that is, they are not well-described using paramteric statistical descriptions. Thes scaling structures as manifested in body mass distirbutions of communities are considered reflective of the  discontinuous and heterogeneous nature of resource use. Specifically, @holling1992cross suggests that the body mass distribution of a community or group of species reflects the discontinuous nature of environmental structures and processes. Quantitative analyses of animal body sizes [@allen2006patterns;@nash2014habitat] and other similar distributions has revealed the prevalence of discontinuous size distributions in faunal body mass [@skillen2008ecological], plant biomass [@spanbauer2016body], city population sizes [@garmestani2005time], and species’ home range size [@restrepo2008discontinuities].

Species operating at similar spatial and temporal scales are those close in body size, and are identified in discontinuity analyses as belonging to the same body mass aggregations or ‘lumps’ (Allen and others 1999). The interactions among species in a single aggregation presumably experience a higher frequency and intensity of interspecific interactions with each other as opposed to those in different aggregations (Peterson and others 1998). 

<!-- In this chapter, I use a Bayesian implementation of classification and regression tree analysis [BCART; @chipman1998bayesian] to statistically identify the discontinuous structure of body mass distributions in avian communities of North America.  -->
<!-- space time. I then identify patterns in the  -->
barichievy2018method - method taht caleb used.

Multiple global change drivers are exerting influence in a south-to-north pattern within the Great Plains. For instance, in the Great Plains, climate change is shifting native and agricultural plant phenologies (Richardson et al., 2013) and geographic centers of species distributions (Hovick et al., 2016). Woody plant encroachment is causing regime shifts from historically grassland regimes to woodland or shrubland regimes (Engle et al., 2008); whole ecoregions in the southern Great Plains have shifted to woodlands in the past century, and northern ecoregions are increasingly on the brink of wholesale regime shifts (Twidwell et al., 2013). Interacting with climate change and woody plant encroachment, fire frequency and size have also increased by >400% in the Great Plains, especially in the southern portions that have transitioned to woodlands (Donovan et al., 2017). Energy development such as oil and gas extraction reduced net primary productivity by approximately 4.5 Tg between 2000-2015, with much of the development focused on the southern Great Plains (Allred et al., 2015). Although the rate of agricultural land conversion had greatly slowed by the 1950s (Brown et al., 2005), the northern plains lost much of its remaining grassland after commodity prices surged at the beginning of the 21st century (Drummond et al., 2012). Urbanization and population growth in the Great Plains has continually increased in and around already populated areas (Brown et al., 2005), with the greatest growth occurring in the southern portions of the Great Plains.
In light of this, we selected a belt transect on the ecotone of the Great Plains and Eastern Temperate Forests extending from the Gulf of Mexico to the edge of the boreal forest in Canada. Specifically, the belt transect extended south-north from 28 - 49 degrees latitude (approximately 2300 km) and east-west from 93 - 97 degrees longitude (approximately 350 km).
Statistical Analysis
Identifying discontinuities
For each route falling within the belt transect, we identified discontinuities in avian community body masses by rank-ordering the log-transformed body masses of each species observed at each route for each year. We obtained mean body mass estimates for all species in the analysis from the CRC Handbook of Avian Body Masses (Dunning Jr, 2007). We then used the “discontinuity detector” method (Barichievy et al., 2018) on the log-ranked body masses, which is based on the Gap Rarity Index for detecting discontinuities in continuous data (C. Stow, Allen, & Garmestani, 2007). For taxa with determinant growth, mean body mass has been shown to reliably differentiate size aggregations and is strongly allometric to the scales at which functions are carried out by organisms (Nash et al., 2014; Sundstrom & Allen, 2014). Because the discontinuity detector method is known to overestimate discontinuities in observations with low species richness, we removed any routes with < 40 species observed within a given year (Table 3.1). We used a power table (Lipsey, 1990) to account for sample size (the number of species observed at each BBS route in a given year) and average variance in body masses (Dunning Jr, 2007) to adjust the critical d-value (the value based on Monte Carlo simulations that identifies significant discontinuities) where N varied (Allen, Forys, & Holling, 1999) (Table 3.2).

## Methods
I used discontinuity analysis to identify the cross-scale structure of the avian communities across space-time [@barichievy2018method]. 

### Spatial sampling scheme
I sampled BBS routes from a North-South-running transect in Central North America running from the Southern Great Plains ecoregion near the Gulf of Mexico ($\sim 28^\circ$ latitude) to boreal Canadaian forest ($\sim 49^\circ$ latitude), running $\sim 5^\circ$ west from ($\sim 93^\circ$ longitude) to ($\sim 97^\circ$ longitude). This region of the world is experience widespread range expansion of a native invasive woody plant, Eastern Redcedar [*Juniperus virginiana*;@twidwell2016plant;@donovan2018social]. This widespread and steadfast transition of native and replanted short and tallgrass prairie habitat to semi-wooded areas should manifest in the avian community composition across large spatial scales, potentially manifesting as changes in cross-scale strucutre of avian body masses. Given the body of evidence suggesting avian community composition shifts upon woody encroachment, we can make two predictions. First, an area undergoing woody encroachment should exhibit a shift in community composition, given the extreme sensitivity of grassland bird species to woody cover. As such, we should next expect a shift in the body mass aggregation structure of the avian community. However, this compositional shift need not manifest in the discontinuous strucutre of the body mass distribution (e.g., shifting the number, size, and/or location of body mass aggregations within a distribution). Rather, at a minimum, we should expect species turnover and potentially shifts in the species which dominate (comprise the center of) or are peripherally associated with (comprise the edges of) each body mass aggregation. 

###

Given the extent and resolution of our data, we are able to only test the biotic interaction and textural discontinuity hypotheses [@allen2006patterns]. 
"If scale‐dependent resource variability is introduced into the model, then a single mode can separate into multiple modes (Marquet et al. 1995), indicating an interaction between the distribution of resources in the landscape and body mass aggregations." from allen2006patterns



