`r if(knitr:::is_latex_output()) '\\appendix'`
`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'` 
<!-- this first appendix line 1 starts the appendix secioning and should be called prior to the references -->
# Appendix A bbsAssistant: an R package for Download and Munging Data and Information from the North American Breeding Bird Survey {-#bbsAssistant}
*[This package is awaiting review at the Journal for Open Source Software](https://github.com/openjournals/joss-papers/tree/joss.01550/joss.01550). JLB is the creator and maintainer of the package. G. Palomo-Mu\~{n}oz and Lyndsie Wszola are co-authors. Tentative doi: 10.21105.joss.01550*

## Package Summary

This package contains functions for downloading and munging data from the North American Breeding Bird Survey (BBS) FTP server [@pardieck2018north; @sauer2017first]. Although the FTP server provides a public interface for retrieving data and analysis results, this package consolidates the efforts of the data user by automating downloading and decompression of .zip data files, downloading route-level information, and saving them as .feather files for speedy import from disk. The data subsetting features of this package also allow the user to readily import and save to file only the data necessary for her purposes. Although the primary audience is for those wishing to use BBS data in Program R for visualization or analysis, this package can be used to quickly download the BBS data to file for use elsewhere. 

The BBS team uses hierarhical modelling techniques to generate population trend estimates [@sauer2017results] at various spatial scales [see the BBS results webpage](https://www.mbr-pwrc.usgs.gov/). Given the variability in data availability, the BBS team also provides data credibility scores for species-regions combinations. This package contains two functions for retrieving the population trend estimates produced by @sauer2017results and the associated data credibility scores: a web-scraping function for obtaining current region and/or species-specific population trend estimates and data credibility scores via a supplied url, [`get_credibility_trends()`](https://github.com/TrashBirdEcology/bbsAssistant/blob/master/R/get_credibility_trends.R); and a function for the current and archived population trends estimates for *all* species and regions, [`get_analysis_results()`](https://github.com/TrashBirdEcology/bbsAssistant/blob/master/R/get_analysis_results.R). 

## Package Vignette
Package vignette is available at [https://github.com/TrashBirdEcology/bbsAssistant/tree/master/vignettes](https://github.com/TrashBirdEcology/bbsAssistant/tree/master/vignettes)

## Package Manual  
For functions and descriptions please see the [manual at github.com/bbsAssistant/tree/master/man](https://github.com/TrashBirdEcology/bbsAssistant/tree/master/man). 

## Acknowledgements

The authors of this package thank the participatory scientists who collect data annually for the North American Breeding Bird Survey, and the Patuxent Wildlife Research Center for making these data publicly and easily accessible. Some functions in this package were adapted from the [rBBS](github.com/oharar/rbbs) package and are mentioned in function source code as appicable.

`r if(knitr:::is_latex_output()) '\\appendix'`
`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'` 
# Appendix B regimeDetectionMeasures: an R package for calculating various regime detection measures {-#regimeDetectionMeasures}  
## Package Summary
This package provides functionality for calculating numerous regime shift detection measures (see below). Additionaly, a 'new' metric, **distance travelled** and __velocity__ are also calculated:

**Composite measures:**  
1. Distance travelled -see also package [`distanceTravelled`](https://github.com/TrashBirdEcology/distanceTravelled).  
1. Fisher Information 
1. Variance Index  

**Single-variable measures:**  
1. Skewness (mean and mode versions)  
1. Kurtosis  
1. Variance  
1. Mean  
1. Mode  
1. Coefficient of variation, CV  
1. Autocorrelation lag-1 (using `stats::acf`)  

Development source code for this package is available on GitHub as a compressed file at [https://github.com/TrashBirdEcology/regimeDetectionMeasures/archive/master.zip](https://github.com/TrashBirdEcology/regimeDetectionMeasures/archive/master.zip) or at [https://github.com/TrashBirdEcology/regimeDetectionMeasures](https://github.com/TrashBirdEcology/regimeDetectionMeasures).


## Package Manual  
For functions and descriptions please see the [manual at github.com/bbsAssistant/tree/master/man](https://github.com/TrashBirdEcology/bbsAssistant/tree/master/man). 

# Appendix C bbsRDM: an R package for applying `regimeDetectionMeasures` functionality to spatial data {-#bbsRDM}

The R package bbsRDM provides a template for using the North American Breeding Bird Survey to calculate various regime detection measures across space. This document provides a guide to to package functionality and results visualization. This package is not actively developed. Development source code for this package is available on GitHub as a compressed file, [https://github.com/TrashBirdEcology/bbsRDM/archive/master.zip ](https://github.com/TrashBirdEcology/bbsRDM/archive/master.zip ) or at [https://github.com/TrashBirdEcology/rRDM](https://github.com/TrashBirdEcology/rRDM).

## Package Vignette
Package vignette is available at [https://github.com/TrashBirdEcology/bbsRDM/tree/master/vignettes](https://github.com/TrashBirdEcology/bbsRDM/tree/master/vignettes). This example provides source code for analyzing the North American Breeding Bird Survey across regularly-sampled spatial transects at one or more points in time.

## Package Manual  
For functions and descriptions please see the [manual at github.com/bbsRDM/tree/master/man](https://github.com/TrashBirdEcology/bbsRDM/tree/master/man). 



`r if(knitr:::is_latex_output()) '\\appendix'`
`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'` 
# Appendix D Functions used to calculate discontinuities in avian body mass distributions. {-#appDiscont}

This code was first published in @barichievy2018method and has been slightly modified and annotated for the purposes of this dissertation. This code was used to produce body mass discontinuities in Chapter \#ref(discontinuity)

## Neutral.Null function
Neutral.Null <- function(log10.data, resolution = 4000) {
  Dmax = max(log10.data, na.rm = FALSE)
  Dmin = min(log10.data, na.rm = FALSE)
  ds = (Dmax - Dmin) / resolution
  MaxK = (Dmax - Dmin) / 2
  MinK = ds * 2
  
  #define h's to analyze
  ks = seq(MinK, MaxK, by = 1 / resolution)
  
  # generate matrix
  bws = matrix(data = NA,
               nrow = length(ks),
               ncol = 1)
  
  for (i in c(1:length(ks))) {
    # Calculate KS density estimate
    KSdens <- density(log10.data, bw = ks[i], "gaussian", adjust = 1)
    
    # Test if the ksdensity is unimodal
    TF <- which(diff(sign(diff(KSdens$y))) == 2) + 1
    if (length(TF) == 0)
      bws[i] = 1
    else
      bws[i] = 0
  }
  # Define the neutral Null
  r = min(which(bws == 1))
  hnull = ks[r]
  return(hnull)
}

## Bootstrapping Function
DD <- function(log10.data, hnull, Sample.N = 1000) {
  NNull <- density(log10.data, bw = hnull, "gaussian", adjust = 1)
  N <- length(log10.data)
  
  # generate matrix
  null.samples <- matrix(data = 0,
                         ncol = Sample.N,
                         nrow = N)
  for (i in 1:Sample.N) {
    #sample the null model
    rand.N <- sample(NNull$x, N, replace = TRUE, prob = NNull$y)
    #calculate the gaps
    null.samples[, i] <- sort(rand.N, decreasing = FALSE)
    #put into the matrxi
  }
  
  # generate gaps
  gaps.log10.data <- diff(log10.data)
  gaps.null.samples <- diff(null.samples, decreasing = FALSE) # difference between random samples and 1st diff orig dat
  gap.percentile <- matrix(data = 0,
                           nrow = length(gaps.log10.data),
                           ncol = 1)
  for (i in 1:length(gaps.log10.data)) {
    # generate distribution of gaps per row (per gap rank)
    gap.percentile[i] <-
      ecdf(gaps.null.samples[i, ])(gaps.log10.data[i]) # returns the percentile at each observation
    
  }
  Bootstrap.gaps <- rbind(gap.percentile, 0)
  Bootstrap.gaps <- cbind(log10.data, Bootstrap.gaps)
  return(Bootstrap.gaps)
}

