# Catch-all, unused, to be removed from pdf {-.unnumbered}
## Random
To be useful to practitioners it may be necessary to move beyond heuristic methods, to methods which supply statistical signifiances or probabilites.

Although critiques of some RDMs exist, the rate at which they are rigorously tested do not exceed the proliferation of new methods in the literature. For any method to gain credible traction as a pragmatic tool in ecology, studies shouldl address the concerns of these critiques. These can be addressed using, e.g., bootstrapping, simulations. 

The number of methods is overwhelming, and although there are quite a few reviews and critiques of RDMs in ecological, they are primarily limited to methods which are (relatively) widely cited or are authored by those wiht high H-indices. As a consequence, case studies of regime shifts often use methods which have been cited multiple times (e.g., variance index). Further, some fo these methods are fairly elegant adn require some level of knowledge to use correctly-- however, are being blindly applied to data. 

Blind application of fancy methods [@steel13applied]
"Absence of enoguh evidence to disprove the null hypothesis is not evidence of the null hypothesis!" [@steel13applied]
Tehre is also the issue of whetehr to transform the data

Signs of multiple attractors present include: hysteresis, path-depdendency (dynanical), bimodality


Leading indicators/regime detection measures of regime shifts using univariate data are well-tested on both theoretical and empirical data [e.g. @burthe2016early]. Among the most widely used RDMs indicators applied to time-series data include an index of variance, moments around the grand mean (skewness and kurtosis), and critical slowing down [@carpenterBrock2006, @carpenter2006rising]. Although univariate indicators may provide insight into relatively simple systems, their, their reliability as indicators for complex systems is less certain [@burthe2015early, @dutta2018robustness, @perretti2012regime, @sommer2017generic, @bestelmeyer_analysis_2011]. Leading indicators can be a reliable warning of impending shift [@carpenterBrock2006],  Some methods have been applied to early-warning indicators in whole systems (Carpenter et al. 2011), however, it is uncommon to have enough information to build reliable networks or food webs. Consequently, reliably measuring the ecological system at hand is often realistically (and financially) not possible.  

Contrary to univariate indicators of regime change, the Fisher Information measure is proposed as a method for identifying changes in a multivariate data set (Fisher 1922, Cabezas and Fath 2002, Karunanithi et al. 2008, Eason and Cabezas 2012, Eason et al. 2014, Ahmad et al. 2016). See Chapter \@ref(#derivatives) for a detailed explanation of the concept of Fisher Information. It is suggested that Fisher Information captures the ecological complexity of a system if given a set of observations which encompass the ecological drivers which dictate the state of the system. A relatively rapid change in the amount of Fisher Information is interpreted as a change in system configuration or orderliness (e.g., see Karunanithi et al. 2008). Fisher Information is rooted in statistics and in the physical sciences-it has only recently been applied to complex ecological and social-ecological systems (Frieden 1998; Fath et al.; Palowski et al). Despite its established use in identifying the degree of predictability of closed systems in physics, Fisher Information's utility in rigorously and universally assessing the state of complex ecological systems is not known. 

## On the complexity of nature
Natural systems are far too complex and chaotic to model wholly, therefore, synthetic models and qantiattive analyses for tracking ecisystems are required to gain further understanding and forecasting (@hastings1993chaos). Improving the tractibility of models of ecological systems requires an understanding that ecological phenomena are non-linear, and that incorporating or accounting for chaotic (stochastic) dynamics is required. 

Creating tractible models or representations of ecological systems requires methods which incorporate both dynamial nonlinearities and noise.

## On analysing ecol time series data 

@hastings1993chaos suggest we ask the following questions of ourselves before analysing ecological tiem series data:
- What questions are being asked? 
- What alternative hypotheses are credible, given what is already known about the system? 
- What assumptions can safely be made about the data? For the questions, hypotheses, and data in hand, what methods are acceptably reliable?

## on improving RDMs
We need the rdms to be able to tell us (1) binary, is there a change point, (2) precision of location of change point, and (3) forecasting next change points

for most ecological systems, there is not sufficient data to use supervised methods (i.e,. we don't usually have enough data for a treaining and testing dataset split), so unsupervised methods are currently ideal -- efforts focused here will be useful in coming years. Additiaonlly, **unsuprvised** methods do not require us to label the data (i.e., no a priori).



## on fisher info
eason2014managing -- "characterziews the behavior of dynamical systems" .This paper compares traditional EWis with FI, sugesting that 
> "Although thresholds and regime shifts appear to be quite closely related concepts, these phenomena are quite distinct. In particular, thresholds are defined as a point where small changes in underlying system variables produce large scale system wide responses and result in sudden and dramatic changes in key properties and system quality (Groffman et al. 2006). On the contrary, regime shifts do not require abrupt tipping points but can be the result of long periods of system reorganization. However, while thresholds do not automatically imply regime shifts, threshold approaches may provide insight into pertinent trends in key variables that coincide with a regime shift."

## On the evidence for ecol regime shifts
@capon2015regime found evidence for regime shifts in nature are limited mostly to freshwater shallow lakes. 

@mac2014scrutiny Authors conducted lit review to search for papers that suggest there was a regime shift, but found that few papers actually found evidence for a *stark* change. Suggest that identifying stark changes is hindered by a few things: 1) terminology, 2) calims based on two obvservations (B and A), 3) what is the frequency of the change, 4) are the changes actually linked to variation in drivers?

Many RDms cannot provide threshold values, because the ecosystems are highly variable, adn cannot ID whether the change was hysteretic -- this is especially true for forecasting middlep-number systems.



In agreemen wiht @mac2014scrutiny, I suggest that stability does not 

## On alternative stable staets
"Inconsistent terminology and vague links...to theory" (@capon...) are hindering advancement of regime shift detection mehtods and theory 

@petraitis2004detection suggest that a good test of showing whether a system has alternative state sis 
> "good test of the theory would simply require showing that a given habitat would support two or more different assemblages of species and that these assemblages were stable"

also from @petraitis2004detection "proof of an alternative community required showing by
experiment that the same site could be occupied by different self-replacing communities (this is by peterson1984 in response to connell and sousa)

lotka1956elements on eof hte first to suggest multipel states of a natural system

"Both Lotka and Lewontin note that constancy does not imply stability and that stability is a
dynamical property" - from @petraitis2004detection


## On critical slowing down    
 
**Critical slowing down** is the most solid theoretical concept in the study of **ecological regime shifts** and is a more precise variant of **Pimm's resilience** (c.f. **Hollings resilience**). The theory is such that the **recovery rate**, or the time it takes to return to a **stable** point, decreases as it nears its **tipping point**.


"the recovery rate should decrease. It occurs because a system???s internal stabilizing forces become weaker near the point where they break and the system moves into a new regime. Thus critical slowing down is posited to exist at phase transitions, such as ecosystem collapse. A system is stable when it is in a deep basin of attraction corresponding to many strong negative feedback loops acting on it. In such a case small perturbations do not have long-term consequences. As a system degrades these negative feedback loops become broken and thus the steepness of the basin of attraction becomes lower.
Its resilience becomes decreased bring the system close to a critical transition. This means that the same perturbation that may not flip the system will though likely take longer to dissipate. Thus it will take longer for the system to return to its point of equilibrium when close to a tipping point. The simplest way to measure the approach to a potential tipping point then would be to directly measure the recovery rate at which the system returns back to its initial equilibrium state following a perturbation. In cases where the system is close to a tipping point, the recovery rate should decrease ??? slow down. As such critical slowing down offers some potential to probe the dynamics of a system in order to assess its resilience and the risk of an upcoming regime shift. ???We have all these complex systems like the brain, the climate, ecosystems, the financial market, that are really difficult to understand, and we will probably never fully understand them. So it???s really kind of a small miracle that across these very different systems, we could find these universal indicators of how close they are to a threshold??? ??? Marten Scheffer""

For multispecies data you will typically need to reduce dimensionality before you can proceed, for example by some sort of ordination. The vegan package for R is typically the starting point for this. I can help you a bit further on the way if you are not familiar with this if you want to, but then I would need to know a bit more about your data.

## Brandolini's principle    
    
- Current state of regime shift theory
- Why it is important to diagnose/detect abrupt changes at the system level
- Current methods are not being employed by ecological management. 
    - Why are applications largely restricted to theoretical research?
    - Why are the applications to empirical data largely restricted to the research community?
    - Is this an artefact of how long it takes for applied ecologists and ecological management to adopt new data anlysis techniques?

## Importance of this thesis  
- Identifying methods for multiple species data
- Highlighting the methods that may or may not be useful to the causal quantitative ecologist

## Some notes on RSDMs not yet in text. 

Ecosystems are complex and we will never fully understand them... "So it???s really kind of a small miracle that across these very different systems, we could find these universal indicators of how close they are to a threshold" - Scheffer

As the scale of the system increases, so does the ability to cahracterise a system in a relevant manner, and also the ability to detect meaningful change int eh ssytem becomes muddier. It is not surprising, therefore, that RSDMs have been relatively well-developed and tested in climatic and marine systems. It is with these data that parametric and non-parametric tests which detect changes in the mean of a system have been most commonly applied. 

If we know or suspect a shift exists, then it is advantageous to know to what disturbances or interventions the system responds/shifts, and at what rate it will cahnge (rapid, slow) (@contamin_indicators_2009).

how to handle systems that are non-stationary
how to handle systems taht are not ergodic?
how do we determine ergodicity of ecosystems? especially when baseline or comparable sites are unavailble. 
If these RSDMs cannot even reliabily and consistently detect RSs, then how are we goign to detect them in time for mangaement/intervention?
All of these methods are assuming that a system is ergodic -- this si especiall yimportnt when examinig systems at scales that are smaller thatn teh underlying process - the system may not look ergodic.
Critical transitions are more concrete than a regime shift -- so it is no surprise that these methods are more explored than for "regime shifts". 

Tipping points are points at which a system responds in a big way to a small chagne, adn much of the theoryand methods are well-developed in this space (e.g. coral reefs @hughes_living_2013,  forests @scheffer2005synergy, insect outbreaks @ludwig1978qualitative, and society @scheffer2003slow). While these RSDMs are  useful for manipulable systems, they are less so for systems of larger scale or extent (e.g. bird communities) and especially for regime shifts occuring due to some uncontrollable circumstance (e.g., climate).

Changes in hte underlying structure or functioning of natural systems due to exogeneous forcings is of interest to climatologists, and terrestrial and aquatic ecologists alike. BEing able to identify and predict these shifts is particularly useful for systems which are actively managed, or are systems that are used by or are beneficial to humans. Being able to predict these shifts in time for management action, or response, is key.

Papers that are critical of RSDMs and RSD include @perretti2012regime, @andersen_ecological_2009, @contamin2009indicators, @perretti2012regime and @contamin2009indicators concluded that some early-warning indicators (skewness, kurtosis, AR1, spectral ratio) perform poorly in the presence noise, but are unaffected by autocorrelation of the noise.  Although most tests of variance as an indicator have fared well (@carpenter_early_2011, @brock_variance_2006), the amount of noise significantly reduces its ability to detect regime shifts (@perretti2012regime).


A goal in ecological RSDM is to move from objective to subjective identification of regime shifts. Probabilistic approaches to RSD are desireable, however, the inherent subjective nature of a regime shift will always make the approach subjective (since the user has to define the system boundaries and what variables can be used to indicate the shift...).

Many papers (e.g. Sundstrom 2017, EasonXX, WAng et al) suggest using multiple indicators when attempting to detect regime shifts, such that inference amogng each is similar. 



## This section contains notes on model-based and metric-based methods for detecting regime shifts

## Types of regime dtection methods
There are two types: model-based and metric-based. Most methods (model- and metric based) try to identifyi regime chagnes by identifying points int eh TS where memory and variability change, and try to fit to a model of critical transitions (e.g., saddle-node, ...).

### Model-based
These methods (see Table XXX) fit the observed time series to a model. 

### Metric-based
These methods do not fit the data to a model, but rather observe changes in various statistical properties of the time series. Model-free metrics are free from highly-parameterized models, allowing for idetifying RS in less-understood systems, or in systems in which reliable mathematical models do not exist. 
- Critical slowing down (CSD) is among the most well-developed theories in natural systems regime shifts, borrowed from dynamical systems theory. It states that, as a system nears a phase transition (or tipping point) it's return or recoery rate should decreased. CSD, however, is difficult to detect in ecosytems which do not exhibit stationary behavior prior to the shift, and/or about which we have little baseline knowledge (with which to compare the system in question). 


Autocorrelation and spectral properties:
critical slowing down (return rate): change in the correlation structuer of the TS, which results in an increase in short-term memory of a system before the transition.
ways to measure AC:

Methods for distinguishing noise form signal were borrowed from information theories, and are well-developed for climatological and oceanographic data. However, there is still debate about white vs red noise. Further, methods in these fields are well-developed for *periodic* or cyclic systems*, or systems with a single, known state attractor. WHen the system does not oscillate around some grand mean system state, the definition and conseuqently the methods for detecting regime changes of the entire system are muddied. 

Numerous quantitative methods are proposed for identifying abrupt changes, or regime shifts, in ecological systems (@andersen_ecological_2009, @roberts2018early). Despite the rapid rate at which these new methods enter the relevant literature, methods for detecting regime shifts remain largely in the theoretical domain. However, significant work has been done on systems exhibiting saddle-node bifurcations (or systems which have some 'tipping point'), where numerous methods for detecting "early-warning signals" (e.g., flickering, rising variance) have been tested in theoretical and empirical data (see @dakos_methods_2012 for an overview of these methods). 


Although early-warning signals have proven useful in some systems (@carpenter2011early), most methods are applicable so sytems First, sudden shifts in dynamics may
occur in the absence of underlying parameter
changes (i.e., in the absence of the tipping point).

cases where systems lose their periodicity 
@hastings2018transient

  
  
  
  
## Some text from the review chapter -
Potential text: 
1. Climate change is expected to induce an increase in both the intensity and frequency of rapid ecological change or disturbance, impacting social systems, potentially to the detriment of human communities most vulnerable. Identifying and forecasting these changes is critical for community and ecological planning, management, and disaster mitigation. 

1. Because ecological and social systems are tightly coupled, we have used indicators in the environment and in wildlife communities to identify change and potential changes that may impact our social communities. 

1. Many regime shift analytical papers suggest that, using multiple quantitative methods to provide for evidence for a regime shift in a specific data set is necessary  [@lindegren_early_2012]. Although this proposition is valid, comparing results within a single system using multiple methods has often yielded varying results. Managing systems using quantitative methods that yield different results may yield improper management techniques and objectives. 


Identifying historic ecolgoical regime changes has been achieved using post-hoc analyitcal approaches Methods for reliably forecasting and predicting these changes are less common. Although numerous quantitative methods exist for detecting ecological regime shifts, new methods are proposed for achieving this aim ata  XXX rate (*insert figure of number of papers per year with new methods*). These methods have proven useful in detecting shifts in atmospheric and fisheries catch data, and in systems that are well-described by a few state variables, or can be modelled reliably with matheamtical equations. Because ecological comunities are more complex than, say, a simple Lotka-Volterra predator prey system, the set of reliable regime shift detection methods narrows. 

Ecological and social-ecolgical systems have many unpredictable and variably interacting components. Quantitative models and methods are available for analyzing complex systems, but often require more data than is typically available in ecological reserach and management. Hence, tracking the changes in ecological systems is rarely done so using multiple variables. 

A survey of the methods available for detecting ecological regime shifts in high dimensional data is timely. Although multiple reviews of regime shift indicators exist, Recent reviews of regime shift indicators (Andersen et al, the others) are outdated, are not comprehensive (include only a subset of the available RSDMs), and do not provide recommendations for which events, systems, or data characterstics are appropriate for these methods. 

Some RSDMs are proposed for and are subsequently applied to data having specific characteristics, while others are proposed to be useful in multiple systems and on data of varying characterstics (e.g., Karunithi et al; Mayer 2007; Eason). This review provides a summary of the available methods and evaluates the appropriateness of these methods to data of varying character, quality, and quantity.

In this chapter I presented a comprehensive overview of quantitative methods proposed as regime detection methods for ecological data. I discuss the relevant characteristics of the data/information that are required for each method, and how these characterstics may help or hinder the ecologists' interpretation of the analytical results. We pay special attention to the RSDMs that are most appropriate for  analysis of high dimensional and noisy ecological data. 


## FISHER BININNGIN SHIT
Fisher Information Interpretation. Researchers using Fisher Information as a measure of complex system order, or as a method for identifying regime shifts in complex systems, present partially numerical approaches to identify periods of rapid change. The methods for pinpointing areas undergoing regime shifts have evolved over the last decade without advancing to an entirely numerical or analytical interpretation. As a consequence, interpretation of Fisher Information in ecological systems is partially subjective, requiring some visual interpretation of Fisher Information trends over time or space. 
	We are currently exploring techniques by which we can alleviate the subjectivity of regime shift identification using Fisher Information in ecological systems via (1) interpolation of observed data or Fisher Information, (2) bootstrapping of original data (abundance) to determine the statistical significance of relative Fisher Information values within a system, and (3) using generalized additive models (GAMs) to estimate the uncertainty in the estimated derivative of Fisher Information (dFI/dt). These approaches are novel to regime shift identification using Fisher Information and will require numerical investigation using simulated data. Furthermore, simulating regime shifts of a complex system will require careful consideration of the system in question, and sensitivity analysis of taxon-specific data requirements in estimating Fisher Information. 
Although equal spacing between points in time (or space) is ideal when estimating system order via Fisher Information, it is not required to use the method. Multivariate data observed about complex ecological systems is inherently noisy. It is this characteristic that prevents us from using a Gaussian process (or kriging) to interpolate Fisher Information between points in noisy data. Bootstrapped species abundances across the entire route to obtain a 95 % confidence interval to determine the expected structure of a disorderly set of systems. We predict bootstrapped data to exhibit little to no trends over time (or space), while real (observed) systems that are not perfectly ordered should exhibit some trend variation. We are exploring the use of generalized additive modelling of Fisher Information to smooth noise and obtain confidence intervals for the derivative of Fisher Information.

Fine-tuning Fisher Information for Use in Ecological Systems. Fisher Information has been shown to identify areas of known regime shift, and can identify known regime boundaries (Sundstrom et al. 2017). To accurately achieve these results, however, the abovementioned studies used data about which regime shifts or spatial regime boundaries (Sundstrom et al. 2017) were known a priori.  For Fisher Information to be tool that is useful for the management of and policy-making regarding ecological and social-ecological systems we must (1) identify the effectiveness of this method in identifying areas actively undergoing change or reorganization and (2) fine tune the implementation of this metric for noisy, ecological process data.
A major component of calculating Fisher Information using this method is the use of a function described as "size of states". Briefly, this method estimates the probability of some percentage of data points (here, species abundances) within a window of data  and has been applied in multiple ways in the ecological literature (e.g., Eason and Cabezas 2012 vs. Sundstrom et al. 2017). 
