---
author: 'Jessica Leigh Burnett'
title: 'Regime Detection Measures for the Practical Ecologist'
date: 'July 31 2019'
institution: 'University of Nebraska-Lincoln'
advisor: 'Craig R. Allen'
altadvisor: 'Dirac Twidwell'
department: 'School of Natural Resources'
degree: 'Doctor of Philosophy'
major: 'Natural Resource Sciences'
knit: "bookdown::render_book"
output: 
 # word_document:
 thesisdown::thesis_pdf: default
acknowledgements: |
  Graduate school itself isn't hard, but the journey is. I have a lot of people and institutions to thank for their emotional, intellectual, financial, and other support. I wish to first highlight how **great it was to be a graduate student at this university and in the School of Natural Resources**. UNL has provided tremendous support at all levels of the university. Although I am not a fan of Nebraska's climate, I highly recommend this school to prospective students.
  \linebreak I thank my supervisors, Craig Allen and Dirac Twidwell, for providing me with this amazing opportunity and for supporting my growth as an independent researcher. I thank my also committee members, Craig Allen, David Angeler, John De Long, Dirac Twidwell, and Drew Tyre for their support and advisement, but especially for their comprehensive examination--I found this process transformative (albeit very stress-inducing). I  parrticularly thank Dirac for his examination questions---I never knew how much I didn't know until I studied your recommendations. I also thank Craig and Dirac for supporting my efforts to study and conduct research in Austria. 
  \linebreak Studying at the International Institute for Applied Systems Analysis was an amazing opportunity! I thank Brian Fath and Elena Rovenskaya for their advisement, members of the Applied Systems Analysis research group for their feedback on my research, and to the postdocs and YSSPers. I owe thanks to Craig Allen and Kevin Pope for entertaining my many hours of discussion (interrogation?) regarding federal employment.
  \linebreak I would like to especially thank some of the amazing and brilliant **female scientists** in my life for their encouragement: Jane Anderson, Karen Bailey, Hannah Birge, Mary Bomberger Brown, Tori Donovan, Brittany Dueker, Allie Schiltmeyer, Katie Sieving, Erica Stuber,  Becky Wilcox, Carissa Wonkka, and Lyndsie Wszola. I thank these women and others for their contributions to my professional development: David Angeler, Christie Bahlai, Mary Bomberger Brown, John Carroll, Jenny Dauer, John DeLong, Tarsha Eason, Brian Fath, Ahjond Garmestani, Chris Lepczyk, Frank La Sorte, Chai Molina, Zac Warren, Hao Ye. I also thank fellow graduate students with whom I forged long-lived personal and professional relationships: Hannah Birge, Tori Donovan, Caleb Roberts, Allie Schiltmeyer, and Lyndsie Wszola.
  \linebreak It is also worth noting that I among those afflicted with mental health "disorders". I am first grafteful to one friend (H) who unknowingly destigmatized mental health in my mind and without whom I may have never sought treatment. I also applaud fellow students and faculty in SNR and UNL who have been active in promoting positive mental health. I am forever  indebtted to my general practitioner and mental health advocate, Terry Thomas M.A., M.S.N., A.P.R.N.
  \linebreak *Financial support*. This research was funded by the U.S. Department of Defense’s Strategic Environmental Research and Development Program (SERDP project ID: RC-2510). The University of Nebraska-Lincoln (UNL) has been highy supportive in my doctoral studies and reserach. I am grateful for the generous of donors to the University of Nebraska Foundation, which provided me with two prestigious supplemental fellowships: Fling and Othmer. I also thank the Nelson Family (Nelson Memorial Fellowship, UNL) for supporting my domestic and international travel to conferences and workshops, and the Institute of Agriculture and Natural Resources, who funded large portions of my academic and research-related travel. I thank the School of Natural Resources for their financial support in my conference travel. The U.S. National Academy of Sciences generously funded part of my travel to the International Institute for Applied Systems Analysis (IIASA). This financial support provided me not only with invaluabe opportunities to attend and present at national and international conferences and workshops, conduct research abroad, and network--this funding alleviated some financial pressures associated with graduate school which allowed a more refined focus on my dissertation research. The opportunities and experiences provided to me by each funding source were amazing, thank you.
    \linebreak Finally, to my partner of eight years--Schultzie--thank you for everything. Just kidding, thank you, Nat Price, you are amazing.
dedication: |
  To those not yet exposed to the great outdoors, first generation college students, Mike Moulton, S, and to myself. 
preface: |
  >"Ecological models are made for ecologists, by ecologists, cooked up for consumption by ecologists---Unknown source"
bibliography: ["bib/thesis.bib", "bib/rdmReview_WOS_20190304.bib", "bib/rdmMethodsReview.bib","bib/packages.bib"]
csl: [reedthesis.cls, csl/globalecol.csl] #csl opts in file: ecology; mee; apa (or list.files("./csl"))
lot: true
lof: true
space_between_paragraphs: true
link-citations: yes
nocite: | 
  @vincent1998technique, @kleinen2003potential, @held2004detection, @carpenter2008leading, @ives2003estimating, @livina2007modified, @biggs2009turning, @andersen_ecological_2009, , @carpenter2006rising, @guttal2008changing, @biggs2009turning, @seekell2011conditional, @carpenterBrock2011early, @ives2012detecting, @carpenter2011early, @ives2012detecting, @carpenter2010early, @ducre2003comparison, @jo2016bayesian, @mauget2003multidecadal, @karl1987approach, @pettitt1979non, @goossens1987recognize, @yonetani1993detection, @alexandersson1986homogeneity, @solow1987testing, @oerlemans1978objective, @buishand1982some, @francis1994decadal, @buishand1982some, @moustakides2009numerical, @brock_variance_2006, @cazelles2008wavelet, @karl1987approach, @rodionov_sequential_2005, @ebbesmeyer19911976, @fath_regime_2003, @solow_test_2005,  @lanzante1996resistant, @gal2010novel,  @tong1990nonlinear, @see gal2010novel,  @he2008new, @pawlowski_identification_2008, @rodionov2004sequential, @parparov2017quantifying, @parparov2015quantifying, @lade2012early, @baker2010new, @qi2016resilience, @pawlowski_identification_2008, @mantua_methods_2004, @wang2011application, @yin2017methods, @easterling1995new, @groger2011analyses, @peterson1998ecological, @zurlini2014early
---
```{r installLoadPkgs, cache = TRUE, echo=FALSE, warning=FALSE, eval=TRUE, message=FALSE}
## IS THIS A QUICKRUN???? FALSE if knitting a final doc, true will not knit all simulations becaues time expensive # i think i disabled this, though?
quickRun<-FALSE
  if(!exists("quickRun")) quickRun <- FALSE
instlLoadPkgs <- function(packages, install = TRUE) {
  if(install){
  k <- packages[!(packages %in% installed.packages()[])];
  if(length(k))
  {install.packages(k, repos='https://cran.rstudio.com/');}
  }
  
  for(package_name in packages)
  {library(package_name,character.only=TRUE, quietly = TRUE);}
}

myPackages <- c( "tidyverse",
                 "pander",
                 "rmarkdown",
                 "ggplot2", 
                 "ggthemes", 
                 "gapminder",
                 "devtools", 
                 "here", 
                 "dplyr",
                 "thesisdown",
                 "bookdown",
                 "kableExtra", 
                 "gganimate", 
                 "sp", 
                 "raster",
                 "feather", 
                 "maps",
                 "gridExtra",
                 "kedd", 
                 "caTools", 
                 "kableExtra",
                 "tvdiff",
                 "deSolve", 
                 # "segmented", # for chapter 3
                 "DiagrammeR", # for chapter 2 (flow chart figure (grViz))
                 "webshot", # a bug with diagrammer requires me to use this when printing to .pdf
                 "revtools" # import tidy bibtex
                 )
                 
                 ipak <- function(pkg){
                 new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
                 if (length(new.pkg))
                 install.packages(new.pkg, dependencies = TRUE)
                 suppressMessages(sapply(pkg, library, character.only = TRUE))
                 }

# Re-install often as these packages are in  development.
# devtools::install_github("trashbirdecology/bbsRDM", force = FALSE)
# devtools::install_github("trashbirdecology/regimedetectionmeasures", force = FALSE)
# devtools::install_github("natbprice/tvdiff", force = FALSE)
# remotes::install_github("noamross/redoc")

```

```{r loadPkgs, include=FALSE }
# Detach all packages just in case...
if(!is.null(sessionInfo()$otherPkgs)) suppressWarnings(suppressMessages(lapply(paste('package:', names(sessionInfo()$otherPkgs),sep=""), detach,character.only=TRUE,unload=TRUE)))

suppressWarnings(suppressMessages(ipak(myPackages)))

# Load additional packages (non-cran)
library(regimeDetectionMeasures, quietly = TRUE) 
library(bbsRDM, quietly = TRUE)
library(tvdiff, quietly = TRUE)
# library(redoc, quietly=TRUE)
```

```{r chunkOptsInd, cache = TRUE, echo=FALSE, warning=FALSE, eval=TRUE, message=FALSE}
# Chunk defaults
require(knitr)
knitr::opts_chunk$set(cache = TRUE, cache.path = "_cache/",
                      message = FALSE, warning=FALSE,
                      eval=TRUE, echo=FALSE, error=FALSE,
                      # include=FALSE, 
                      fig.pos = 'h',
                      fig.align='center', out.width = "85%")
```

```{r panderOpts, cache=TRUE, echo=FALSE, warning=FALSE, eval=TRUE, message=FALSE}
panderOptions('knitr.auto.asis', TRUE)
```

# Abstract {.unnumbered}

<!-- Do not remove the line with the  '.unnumbered' -->
<!-- There is something buggy about it, when I remove it shit goes bananas.  -->
<!-- Need to figure out how to fix because it inserts like two blank pages! -->

