---
title: "Regime Detection Methods for the Practical Ecologist"
subtitle: "**Jessica L. Burnett**"
author: "<br><font color='black'><b>Co-advisors</b></font>: C.R. Allen & D. Twidwell <br> <font color='black'><b>Committee</b></font>: D.G. Angeler, J.P. DeLong, & A.J. Tyre <br>"
institute: "<br>Nebraska Cooperative Fish & Wildlife Research Unit<br> School of Natural Resources <br> University of Nebraska-Lincoln"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["css/myFonts.css", "css/myTheme.css"]
    chakra: libs/remark-latest.min.js # to load the last saved verion for offline use
    nature:
      beforeInit: "http://www.jvcasillas.com/ru_xaringan/js/ru_xaringan.js"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:7"
---
```{r setup, message=FALSE, warning=FALSE, cache=TRUE, echo=FALSE}
xaringan::summon_remark(version = "latest", to = "libs/")
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(include = FALSE, warning=FALSE, message=FALSE, cache=TRUE, fig.path="/figures")

# PACKAGES
pkgs <- c("tidyverse", "here", "xaringan", "knitr")
# create a function to load packages
loadPkgs <- function(packages) {
  for(package_name in packages)
  {library(package_name,character.only=TRUE, quietly = TRUE);}
}
loadPkgs(pkgs)

# SET PLOT THEME
theme_set(theme_bw())
```

# Ecosystems are Complex <!-- intro -->  
  high dimensional    
  many ($\infty$) interactions  
  non-linear  
  non-ergodic (open)   
  dynamic  

???
Ecosystems are complex; that is, they are non-ergodic,  high-dimensional and usually non-linear. 

---

---
# Dissertation Aims 
<font size="11">
1. sldkfjds  <br>
2. 
</font>
---
# Dissertation Overview <!-- intro -->
<!-- -------    -->
### __Chapter 2__: Review of regime shift detection measures  
--

### __Chapter 3__: Deconstructing the Fisher Information method

--
### __Chapter 4__: Spatial application of the Fisher Information

--
### __Chapter 5__: Proposed method: rate of change of phase space trajectory  

--
### __Chapter 6__: Effects of data loss on regime detection measures  

--
### __Chapter 7__: Discontinuity analysis of avian body mass distributions  

---


# Chapter 2: Aims & Approach
## Census & Review of Regime Shift Detection Measures  

.pull-left[
### __Aim__  
+ Census the ecological literature for quantitative methods

]

.pull-left[
### __Approach__  
Systematic literature review    
Bibliographic analysis
]

---

# Chapter 2: Literature Review Methods
.left-column[
### Bibliographic Analysis
]
.right-column[
`sdkfjsdfkljs`
]


---
# Chapter 2: Results

### $> 70$ methods proposed in literature
### $\sim 10$ suitable for multivariable data
### few explicitly handle noisy data
### few handle irregular sampling

---


